/** Type definitions for Endcoder Pro encoding functions */

export declare function encodeBase64(input: string): string;
export declare function decodeBase64(input: string): string;
export declare function encodeBase64URL(input: string): string;
export declare function decodeBase64URL(input: string): string;
export declare function encodeHex(input: string): string;
export declare function decodeHex(input: string): string;
export declare function encodeBase32(input: string): string;
export declare function decodeBase32(input: string): string;
export declare function encodeBase32Hex(input: string): string;
export declare function decodeBase32Hex(input: string): string;
export declare function encodeUUEncode(input: string): string;
export declare function decodeUUEncode(input: string): string;
export declare function encodeQuotedPrintable(input: string): string;
export declare function decodeQuotedPrintable(input: string): string;
export declare function encodePercent(input: string): string;
export declare function decodePercent(input: string): string;
export declare function encodeBase58(input: string): string;
export declare function decodeBase58(input: string): string;
export declare function encodeAscii85(input: string): string;
export declare function decodeAscii85(input: string): string;
export declare function encodeROT13(input: string): string;
export declare function decodeROT13(input: string): string;
export declare function encodeCaesar(input: string, shift?: number): string;
export declare function decodeCaesar(input: string, shift?: number): string;
export declare function encodeHTMLEntities(input: string): string;
export declare function decodeHTMLEntities(input: string): string;
export declare function encodeAtbash(input: string): string;
export declare function decodeAtbash(input: string): string;
export declare function encodeBinary(input: string): string;
export declare function decodeBinary(input: string): string;
export declare function encodeMorse(input: string): string;
export declare function decodeMorse(input: string): string;

export interface Encodings {
  encodeBase64: typeof encodeBase64;
  decodeBase64: typeof decodeBase64;
  encodeBase64URL: typeof encodeBase64URL;
  decodeBase64URL: typeof decodeBase64URL;
  encodeHex: typeof encodeHex;
  decodeHex: typeof decodeHex;
  encodeBase32: typeof encodeBase32;
  decodeBase32: typeof decodeBase32;
  encodeBase32Hex: typeof encodeBase32Hex;
  decodeBase32Hex: typeof decodeBase32Hex;
  encodeUUEncode: typeof encodeUUEncode;
  decodeUUEncode: typeof decodeUUEncode;
  encodeQuotedPrintable: typeof encodeQuotedPrintable;
  decodeQuotedPrintable: typeof decodeQuotedPrintable;
  encodePercent: typeof encodePercent;
  decodePercent: typeof decodePercent;
  encodeBase58: typeof encodeBase58;
  decodeBase58: typeof decodeBase58;
  encodeAscii85: typeof encodeAscii85;
  decodeAscii85: typeof decodeAscii85;
  encodeROT13: typeof encodeROT13;
  decodeROT13: typeof decodeROT13;
  encodeCaesar: typeof encodeCaesar;
  decodeCaesar: typeof decodeCaesar;
  encodeHTMLEntities: typeof encodeHTMLEntities;
  decodeHTMLEntities: typeof decodeHTMLEntities;
  encodeAtbash: typeof encodeAtbash;
  decodeAtbash: typeof decodeAtbash;
  encodeBinary: typeof encodeBinary;
  decodeBinary: typeof decodeBinary;
  encodeMorse: typeof encodeMorse;
  decodeMorse: typeof decodeMorse;
}
